### ISSUE TITLE
Solr is NOT supported in PHP7

### ISSUE THREAD

**Issue by dlutxx** [gophp7/gophp7-ext#29]
The latest solr extension( version 2.3.0 as of this writing) won't compile with PHP7, and generates the following error:  

```
In file included from /usr/local/php7/include/php/Zend/zend.h:36:0,
                 from /usr/local/php7/include/php/main/php.h:35,
                 from /home/dev/solr-2.3.0/php_solr.h:28,
                 from /home/dev/solr-2.3.0/php_solr.c:23:
/usr/local/php7/include/php/Zend/zend_hash.h:57:29: note: expected ‘dtor_func_t’ but argument is of type ‘void (*)(void *)’
 ZEND_API void ZEND_FASTCALL _zend_hash_init(HashTable *ht, uint32_t nSize, dtor_func_t pDestructor, zend_bool persistent ZEND_FILE_LINE_DC);
                             ^
/home/dev/solr-2.3.0/php_solr.c:1305:2: error: void value not ignored as it ought to be
  if (zend_hash_init(SOLR_GLOBAL(functions), nSize, NULL, solr_destroy_function, persistent) == FAILURE) {
  ^
make: *** [php_solr.lo] Error 1
```

gcc version: `gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)`

**Comment by 0mars** [comment]
Hello @dlutxx, 2.3.0 does not support php7
The PHP 7 support along with optimizations is still in progress, it used to be under the php7 branch, now its on master.

**Comment by dlutxx** [comment]
Hi @0mars , so I cannot use Solr in PHP7 now?
I just tried your repo `pecl-search_engine-solr`, but it wont compile.

**Comment by 0mars** [comment]
Hello @dlutxx 
'master' compiles on php 7.0.0, and 7.0.2. I'm still working on some bugs.
The code coverage is bad, so if you or anyone who sees this post would like to contribute, please feel free to contact me for instructions.
No C knowledge is required for contributing tests.

**Comment by dlutxx** [comment]
Hi @0mars , that's great. I'd like to help. Any instructions to follow?

**Comment by SergeyBear** [comment]
Hello!
I did compile from latest master, but all make tests are failed and when loading module I get error:

PHP Warning:  PHP Startup: Unable to load dynamic library '/root/downloads/pecl-search_engine-solr-master/modules/solr.so' - /root/downloads/pecl-search_engine-solr-master/modules/solr.so: undefined symbol: solr_string_release in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/root/downloads/pecl-search_engine-solr-master/modules/solr.so' - /root/downloads/pecl-search_engine-solr-master/modules/solr.so: undefined symbol: solr_string_release in Unknown on line 0

Any ideas?

**Comment by 0mars** [comment]
@dlutxx 
We'll start with building a coverage report using the following script
```
./scripts/test-coverage.sh
```
It cleans, builds, runs the test suite and generates a coverage report in the 'report' directory on the extension's path

To run a single test case you can do as follows:
```make test TESTS=tests/008.solrclient_commit.phpt```

You can skip the uncovered lines, and internal methods within any file that does not start with php_, and work only on the whole methods that haven't been covered.

For instance
SolrParams::getParams() at: https://github.com/php/pecl-search_engine-solr/blob/master/php_solr_params.c#L761

Please use the PHP QA Guide: http://qa.php.net/write-test.php.

For the Solr extension, there are 2 types of tests, 
1. Tests that do not require a Solr Server (some of them use fixture files)
2. Requires a running server with cores present and populated with data.

There is a configuration file for the test suite, located at tests/test.config.inc
It contains the fixture file definitions and other configurations for the Solr Server to be used for testing.

To run the type 2 tests, you'll need docker to run the test server using the following command:
``` docker run -p 8983:8983 --name solr5 -t omars/solr53 ```

you'll need to modify the tests/test.config.inc appropriately to enable the the tests.

Please excuse me if I'm being too verbose.

Thanks, much appreciated, if you need any assistance you can reach me by email, or on IRC EFNET #php.pecl

**Comment by 0mars** [comment]
@SergeyBear I have pushed a fix, thanks for reporting.

**Comment by SergeyBear** [comment]
Thank you for reply!
I tried to run ./scripts/test-coverage.sh and got following error after build:

Reading tracefile coverage.info
Removing /usr/include/curl/typecheck-gcc.h
Removing /usr/include/php/Zend/zend_hash.h
Removing /usr/include/php/Zend/zend_smart_str.h
Removing /usr/include/php/Zend/zend_string.h
Removing /usr/include/php/Zend/zend_types.h
Removing /usr/include/php/Zend/zend_variables.h
Removing /usr/include/php/ext/json/php_json.h
Deleted 7 files
Writing data to coverag.info
Summary coverage rate:
  lines......: 0.0% (0 of 7504 lines)
  functions..: 0.0% (0 of 557 functions)
  branches...: no data found
Capturing coverage data from .
Found gcov version: 4.8.5
Scanning . for .gcda files ...
geninfo: ERROR: no .gcda files found in .!

No file .gcda indeed in source or its subdirectories. After some googling found that error may occur when --coverage parameter is missing, but it specified in script, so it probably not that case. Investigating further...

**Comment by SergeyBear** [comment]
Tried to build latest master - now its:
Warning: PHP Startup: Unable to load dynamic library '/root/source/pecl-search_engine-solr-master/modules/solr.so' - /root/source/pecl-search_engine-solr-master/modules/solr.so: undefined symbol: php_json_decode_ex in Unknown on line 0

**Comment by SergeyBear** [comment]
It was https://bugs.php.net/bug.php?id=67140 that cause undefined symbol: php_json_decode_ex.
When json module loaded first - no error appears!
Thank you!

**Comment by 0mars** [comment]
@SergeyBear script fixed, please pull.

About the json error, it requires the json ext

**Comment by SergeyBear** [comment]
Json module was loaded before building.
I pulled latest master and run test-coverage.sh - now it pass all test that does not require solr server and no  error about php_json_decode_ex appears.
Thank you!

**Comment by oerdnj** [comment]
@0mars Does it support PHP 5.x and PHP 7.x (as good behaved extensions do) or do you need to have different versions for 5.x and 7.x?

**Comment by 0mars** [comment]
@oerdnj 2.4.0 supports both PHP 5 and 7

**Comment by 0mars** [comment]
2.4.0 is out, thank you for your patience, Cheers!

**Comment by oerdnj** [comment]
Thanks I have just updated DEB packaging (but it will be stuck in NEW queue for while because of name change from php5-solr to php-solr).

**Comment by demonspeed** [comment]
JSON is built-in. Using php7. Why do I get the undefined symbol: php_json_decode_ex error? If I add extension=json.so to php.ini, it works but complains: PHP Warning:  Module 'json' already loaded in Unknown on line 0. Installed with pecl install solr.

**Comment by 0mars** [comment]
@demonspeed I think you have a load priority problem, if you are using the --with-config-file-scan-dir
please make sure to that solr.ini has a lower load priority.
Example:
20-json.ini
21-solr.ini

You can execute:
```php -i | grep ini```
to know which ini files are loaded.

Hope that helps!

**Comment by hierony94** [comment]
Hello @oerdnj ,
How can I get php-solr for PHP7.0 in Debian Jessie machine?
Have searching for a while, but don't find any.

Thank You.

**Comment by oerdnj** [comment]
@hierony94 https://deb.sury.org/ (section about Debian DPA)

**Comment by hierony94** [comment]
Thanks @oerdnj .
You've saved my time.

**Comment by versaille18** [comment]
Hello,
I cannot get the compiled DLL running with PHP 7.
My setup: Zend Server 9 with PHP 7, WIN10, Apache 2.4.
When I copy the x86 NTS version of php_solr.dll to the extension folder, uncomment the extension in php.ini and restart Zend Server, the error log simply says: cannot find the module specified.

With Zend Server 8.5 and PHP 5.6 it runs fine.

Thanks,
 Chris

**Comment by 0mars** [comment]
@versaille18 please follow up on bugs.php.net
